accounts/urls.py
from django.urls import path
from django.contrib.auth import views as aut_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('<int:profiled_user_id>', views.user_profile, name="user_profile"),
    path('<int:profiled_user_id>/update', views.update_user_profile, name="update_user_profile"),
    path('<int:profiled_user_id>/settimezone', views.set_timezone, name="set_user_timezone"),

    path('testing', views.testdata, name="test_data"),
    path('createusers', views.create_users, name="create_users"),
    path('resetusers', views.reset_users, name="reset_users"),
]

cart/urls.py
from django.urls import path, include, register_converter
from . import views

app_name = 'cart'

urlpatterns = [
    # cart/
    path('', views.view_cart, name="cart_details"), # views.CategoryDetail.as_view(), name="category_details"),
    path('<int:product_id>/', views.add_to_cart, name="add_to_cart"), # views.CategoryCreate.as_view(), name="category_add"),
    path('<int:product_id>/remove/', views.remove_from_cart, name="remove_from_cart"),
    path('<int:product_id>/update/', views.update_cart, name="update_cart"),
    # path('<int:pk>/delete/', views.CategoryDelete.as_view(), name="category_delete"),
    path('test/', views.test_cart, name="test_cart"),
    path('test/<int:new_cart_id>/', views.test_cart, name="test_cart"),
    path('clear-id/', views.clear_cart_id_from_session, name="clear_cart_id"),
    path('revive/', views.revive_cart, name="revive_cart"),
    path('get-id/', views.get_cart_id, name="get_cart_id"),
]

shop/urls.py
from django.urls import path, include, register_converter
from . import views, converters

app_name = 'shop'
register_converter(converters.NegativeIntConverter, 'negint')

ajax_patterns = [
    # ajax
    path('favorite/<int:product_id>/', views.ajax_favorite, name="ajax_favorite"),
    path('unfavorite/<int:product_id>/', views.ajax_unfavorite, name="ajax_unfavorite"),
]

products_patterns = [
    # products/
    # path('<int:category_id>',views.CategoryProductList.as_view(), name="category_products"),
    # path('favorites', views.FavoriteProductList.as_view(), name="favorite_products"),
    # path('search', views.search_products, name="search_products"),
    path('sale', views.SaleProductList.as_view(), name="sale_products"),
    path('recent/', views.RecentProductsView.as_view(), name="recent"),
    path('recent/clear/', views.clear_recent, name="clear_recent"),
]

product_patterns = [
    # product/
    path('add/', views.ProductCreate.as_view(), name='product_add'),
    path('<int:pk>/', views.ProductDetail.as_view(), name="product_details"),
    path('<int:pk>/update/', views.ProductUpdate.as_view(), name="product_update"),
    path('<int:pk>/delete/', views.ProductDelete.as_view(), name="product_delete"),
    path('<int:pk>/promotion/', views.PromotionCreate.as_view(), name="product_sale"),
    path('<int:product_id>/rate/', views.rate_product, name="rate_product"),
    path('<int:product_id>/question/', views.question_product, name="question_product"),
    path('<int:product_id>/favorite/', views.favorite, name="favorite"),
    path('<int:product_id>/unfavorite/', views.unfavorite, name="unfavorite"),
    path('<int:product_id>/getinfo/', views.get_product_info, name="get_product_info"),
    path('product_photo/<int:product_photo_id>/delete/', views.product_photo_delete, name="product_photo_delete"),
    path('product_photo/<int:product_photo_id>/makeprimary/', views.product_photo_make_primary, name="product_photo_make_primary"),
]

sale_patterns = [
    # sale/
    path('add/', views.SaleCreate.as_view(), name='sale_add'),
    path('<int:pk>/', views.SaleDetail.as_view(), name="sale_details"),
    path('<int:pk>/update/', views.SaleUpdate.as_view(), name="sale_update"),
    path('<int:pk>/delete/', views.SaleDelete.as_view(), name="sale_delete"),
    path('<int:sale_id>/getinfo/', views.get_sale_info, name="get_sale_info"),
]

promotion_patterns = [
    # promotion/
    path('add/', views.PromotionCreate.as_view(), name='promotion_add'),
    path('<int:pk>/', views.PromotionDetail.as_view(), name="promotion_details"),
    path('<int:pk>/update/', views.PromotionUpdate.as_view(), name="promotion_update"),
    path('<int:pk>/delete/', views.PromotionDelete.as_view(), name="promotion_delete"),
]

category_patterns = [
    # category/
    # path('', views.CategoryList.as_view(), name="categories"),
    path('add/', views.CategoryCreate.as_view(), name="category_add"),
    path('<int:pk>/', views.CategoryDetail.as_view(), name="category_details"),
    path('<int:pk>/update/', views.CategoryUpdate.as_view(), name="category_update"),
    path('<int:pk>/delete/', views.CategoryDelete.as_view(), name="category_delete"),
]

collection_patterns = [
    # collection/
    path('add/', views.CollectionCreate.as_view(), name="collection_add"),
    path('<int:pk>/', views.CollectionDetail.as_view(), name="collection_details"),
    path('<int:pk>/update/', views.CollectionUpdate.as_view(), name="collection_update"),
    path('<int:pk>/delete/', views.CollectionDelete.as_view(), name="collection_delete"),
    path('<int:collection_id>/getinfo/', views.get_collection_info, name="get_collection_info"),
]

urlpatterns = [
    path('', views.ProductList.as_view(), name='index'), #views.index, name="index"),
    path('product/', include(product_patterns)),
    path('products/', include(products_patterns)),
    path('promotion/', include(promotion_patterns)),
    path('promotions/', views.PromotionList.as_view(), name="promotions"), # list of promotions
    path('sale/', include(sale_patterns)),
    path('sales/', views.SaleList.as_view(), name="sales"), # list of sales
    path('category/', include(category_patterns)), # adding, deleting, updating, viewwing individual categories
    path('categories/', views.CategoryList.as_view(), name="categories"), # list of categories
    path('categories/<int:category_id>',views.CategoryProductList.as_view(), name="category_products"), # products related to categories    
    path('collection/', include(collection_patterns)), # adding, deleting, updating, viewwing individual collections
    path('collections/', views.CollectionList.as_view(), name="collections"), # list of collections
    path('collections/<int:collection_id>',views.CollectionProductList.as_view(), name="collection_products"), # products related to collections
    path('ajax/', include(ajax_patterns)),
    path('favorites/', views.FavoriteProductList.as_view(), name="favorite_products"),
    path('rating/<int:rating_id>/vote/<negint:score>', views.rating_vote, name="rating_vote"),
    path('question/<int:question_id>/answer', views.answer_question, name="answer_question"),
    path('question/<int:question_id>/follow', views.follow_question, name="follow_question"),
    path('question/<int:question_id>/unfollow', views.unfollow_question, name="unfollow_question"),
    path('contact/', views.ContactCreate.as_view(), name='contact-us'),
    # path('contact/success/',views.ContactSuccess.as_view(),'contact-success'),
    # path('test/', views.test, name="test"),
]

weybridge/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('registration/', include('accounts.urls')),
    path('backlog/', include('backlog.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/views.py
from datetime import datetime

from django.conf import Settings, settings
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Avg, F, Q, Count, Sum, Max
from django.http import Http404
from django.shortcuts import render, redirect, reverse, get_object_or_404,HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView,DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from ipware import get_client_ip

from weybridge.settings import CART_EMPTY_CART_ID

from .models import *
from shop.models import Product

@staff_member_required
def test_cart(request, new_cart_id=None):
    """
    Changes cart_id in session to new_cart_id for testing purposes.    
    Creates a copy of cart_id in old_cart_id in session.
    """
    
    try:
        cart_id = request.session['cart_id']
        request.session['old_cart_id'] = cart_id

    except KeyError: #no cart_id key in request.session
        messages.info(request,"CART TESTING: No cart_id in session.")
        cart_id = None

    if not new_cart_id:
        max_cart_id = Cart.objects.aggregate(Max('id'))['id__max'] or 0
        new_cart_id = max_cart_id + 1

    request.session['cart_id'] = new_cart_id
    messages.success(request,f"CART TESTING: Successfully updated cart_id from {cart_id} to {new_cart_id}.")

    return redirect(reverse_lazy('cart:cart_details'))

@staff_member_required
def get_cart_id(request):
    """
    Returns value of cart_id in session for testing purposes.    
    """
    
    try:
        cart_id = request.session['cart_id']
        messages.info(request,f"CART TESTING: cart_id = {cart_id}.")

    except KeyError: #no cart_id key in request.session
        messages.info(request,"CART TESTING: No cart_id in session.")

    return redirect(reverse_lazy('cart:cart_details'))

@staff_member_required
def revive_cart(request):
    """
    Revives cart_id in session by copying from old_cart_id for testing purposes.    
    """
    
    try:
        cart_id = request.session['old_cart_id']
        del request.session['old_cart_id']
        request.session['cart_id'] = cart_id
        messages.success(request,f"CART TESTING: Successfully revived cart_id to {cart_id}.")

    except KeyError: #no cart_id key in request.session
        messages.info(request,"CART TESTING: No old_cart_id in session.")

    return redirect(reverse_lazy('cart:cart_details'))

@staff_member_required
def clear_cart_id_from_session(request):
    """
    Deletes cart_id from session for testing purposes.
    """

    try:
        cart_id = request.session['cart_id']
        del request.session['cart_id']
        messages.success(request,f"CART TESTING: Successfully cleared cart_id {cart_id}.")

    except KeyError: #no cart_id key in request.session
        messages.warning(request,"CART TESTING: No cart_id in session.")

    return redirect(reverse_lazy('cart:cart_details'))

def get_or_create_cart(request):
    try:
        cart_id = request.session['cart_id']

        # if cart_id == settings.CART_EMPTY_CART_ID:
        #     # anonymous user cart_id, so create a cart object but do not store in database
        #     cart_json = request.session.get['cart',{}]
        #     cart = Cart(cart_json)

        # else:
        # cart = Cart.objects.get(id=cart_id)
        cart, created = Cart.objects.get_or_create(
            id=cart_id,
            defaults = {
                'user': request.user,
                'created_by': request.user,
                'updated_by': request.user,
            }
        )

        if created:
            # cart_id from request.session was not in database, so update session
            request.session['cart_id'] = cart.id

    except KeyError: #no cart_id key in request.session, so create one
        # try:
        cart = Cart(user=request.user,created_by=request.user,updated_by=request.user)
        cart.save()
        request.session['cart_id'] = cart.id

        # except:
        #     # user is not authenticated, so the attempt to create the cart above will fail
        #     # just create new empty cart
        #     cart = Cart()
        #     request.session['cart_id'] = settings.CART_EMPTY_CART_ID

    return cart

def get_cart(request):
    """
        Get a cart, if it exists, 
        but don't create the cart if it does not exist .
    """
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
    except:
        # let whatever error occurs (e.g., KeyError if cart_id not in session,
        # or DoesNotExist if found cart_id is not in the database).

        raise 

    return cart

def view_cart(request):
    empty_message = "What's this? Your cart is empty. Please keep shopping!"
    context = {
        'cart': None,
        'empty': True,
        'empty_message': empty_message,
    }
    template =  'cart/cart_detail.html'
    
    # if not request.user.is_authenticated:
        # try:
            # cart_json = request.session['cart']
            # cart = Cart(cart_json)
            # context.update({
            #     'cart': cart,
            #     'empty': cart.item_count == 0, # boolean
            # })
            # refresh cart items (e.g., if an item has gone on sale since adding 
            # to cart, the line total will need to be updated)
            # cart.refresh_cart(request.user)

    #     except KeyError: # no cart object in database
    #         context.update({
    #             'empty': True,
    #         })

    # else:
    # don't create the cart if it does not exist 
    try:
        # cart_id = request.session['cart_id']
        # cart = Cart.objects.get(id=cart_id)
        cart = get_cart(request)

        # refresh cart items (e.g., if an item has gone on sale since adding 
        # to cart, the line total will need to be updated)
        cart.refresh_cart(request.user)
    
        context.update({
            'cart': cart,
            'empty': cart.item_count == 0, # boolean
        })

    except KeyError: #no cart_id key in request.session
        # cart_id = None
        context.update({
            'empty': True,
        })

    except Cart.DoesNotExist: #cart_id is not in database
        context.update({
            'empty': True,
        })

    return render(request, template, context)

@login_required
def add_to_cart(request,product_id):
    if request.method == "POST":
        quantity = request.POST.get('qty',1)

        try:
            quantity = int(quantity)
        except:
            raise Http404("Invalid quantity.")

        cart = get_or_create_cart(request)
        product = get_object_or_404(Product,pk=product_id)

        # if cart.id == setting.CART_EMPTY_CART_ID:
        #     #Cart stored in session only so manually add item json to cart object
        #     pass

        # if the CartItem does not exist already, create it with quantity
        item, created = CartItem.objects.get_or_create(
            cart=cart, 
            product=product, 
            defaults={'quantity': quantity}
        )

        if not created: # the item was already in cart, so just update quantity
            item.quantity += quantity

        # item.line_total = item.product.price * float(item.quantity)
        item.line_total = item.product.get_sale_price() * item.quantity
        item.save()
        
        # cart.item_count += quantity
        # cart.total = cart.items.aggregate(Sum('line_total'))['line_total__sum']
        # cart.updated_by = request.user
        # cart.save()
        cart.refresh_cart(request.user)
        request.session['cart_item_count'] = cart.item_count

        return HttpResponseRedirect(reverse('cart:cart_details'))

    else:   #Ignore GET requests
        return redirect('/')

def remove_from_cart(request,product_id):
    # cart = get_or_create_cart(request)
    if request.method == "POST":
        quantity = request.POST.get('qty',1)

        try:
            quantity = int(quantity)
        except:
            raise Http404("Invalid quantity.")

        # if the cart does not exist, you can't remove anything from it
        try:
            # cart_id = request.session['cart_id']
            # cart = Cart.objects.get(id=cart_id)
            cart = get_cart(request)

        except KeyError: #no cart_id key in request.session
            raise Http404("No cart exists. Cannot complete remove operation.")
        except Cart.DoesNotExist: # cart_id from session is not in database
            raise  Http404("Cart is not in the database. Cannot complete remove operation.")
        
        product = get_object_or_404(Product,pk=product_id)

        try:
            item = CartItem.objects.get(cart=cart,product=product)
        except CartItem.DoesNotExist:
            raise Http404("No cart item matches the given query. Cannot complete remove operation.")
        
        item.quantity -= quantity
        if item.quantity > 0:
            # item.line_total = item.product.price * float(item.quantity)
            item.line_total = item.product.get_sale_price() * item.quantity
            item.save()
        else:
            item.delete()

        # cart.item_count -= quantity
        # cart.total = cart.items.aggregate(Sum('line_total'))['line_total__sum']
        # cart.updated_by = request.user
        # cart.save()

        cart.refresh_cart(request.user)
        request.session['cart_item_count'] = cart.item_count

        return HttpResponseRedirect(reverse('cart:cart_details'))
    else:
        return redirect('/')

def update_cart(request,product_id):
    """
        Similar to add_to_cart(). However, this just updates quantity of 
        product_id to whatever is in request.GET['qty']
    """

    if request.method == "POST":

cart/templates/cart/cart_detail.html
{% extends 'shop/base.html' %}
{% load static humanize %}

{% block css %}
<link rel="stylesheet" href="{% static 'shop/css/product.css' %}">
{% endblock css %}

{% block greeting %}{% if user.is_authenticated %} {{ user.first_name }}{% else %}{% endif %}{% endblock greeting %}

{% block favorites %}
{% if user.is_authenticated %}
<a href="{% url 'shop:favorite_products' %}" class="nav-link"><i class="fas fa-bookmark"></i>Favorites</a>
{% else %}
{% endif %}
{% endblock favorites %}

{% block profile %}
{% if user.is_authenticated %}
<a href="{% url 'accounts:user_profile' profiled_user_id=user.id %}" class="nav-link"><i
        class="fas fa-user-cog"></i>Profile</a>
{% else %}
<a href="{% url 'accounts:signup' %}" class="nav-link"><i class="fas fa-user-cog"></i>Register</a>
{% endif %}
{% endblock profile %}

{% block login %}
{% if user.is_authenticated %}
<a href="{% url 'logout' %}" class="nav-link"><i class="fas fa-sign-out-alt"></i>Logout</a>
{% else %}
<a href="{% url 'login' %}" class="nav-link"><i class="fas fa-sign-in-alt"></i>Login</a>
{% endif %}
{% endblock login %}

{% block content %}
<div class="container">
    <div class="header d-flex flex-column align-items-center" style="margin:10px auto">
        <h1 class="my-0">Your Cart</h1>
        <a href="/"><small>Continue Shopping</small></a>
    </div>

    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    {% endif %}

    {% if empty %}
    <h2>{{ empty_message }}</h2>
    {% else %}
    <table class="table">
        <thead class="text-muted" style="font-weight:normal;">
            <th>Item</th>        
            <th>Price</th>        
            <th>Quantity</th>        
            <th>Subtotal</th>        
        </thead>
        <tfoot>
            <th><a href="/"><small>Continue Shopping</small></a></th>        
            <th></th>        
            <th style="text-align: right;font-weight: bold;">Total</th>        
            <th>${{ cart.total|floatformat:2|intcomma }}</th>        
        </tfoot>
        <tbody>
            {% for item in cart.items.all %}
            <tr>
                <td class="d-flex">
                    <img src="{{ item.product.get_default_photo_url }}" alt="{{ item.product.name }}" style="width:80px;">
                    <span class="d-flex flex-column ml-2">
                        <a href="{% url 'shop:product_details' pk=item.product.id %}">{{ item.product.name }}</a>
                        {% if item.product.is_on_sale %}
                        <small style="color:red">{{ item.product.get_sale }}</small>
                        {% endif %}
                    </span>
                </td>
                <td>
                    {% if item.product.is_on_sale %}
                    <span class="d-flex flex-column align-items-start ml-2">
                        <small class="strike-through">{{ item.product.price|floatformat:2|intcomma }}</small>
                        <small style="color:red">{{ item.product.get_sale_price|floatformat:2|intcomma }}</small>
                    </span>                    
                    {% else %}
                    {{ item.product.price|floatformat:2|intcomma }}
                    {% endif %}
                </td>
                <td>
                    <form method="POST" action="{% url 'cart:update_cart' product_id=item.product.id %}" class="d-inline-flex justify-content-start align-items-center">
                        {% csrf_token %}
                        <input type="number" name="qty" min="0" max="{{ item.product.inventory_stock }}" value="{{ item.quantity }}" style="max-width:4em;min-width:4em;padding-left:3px;">
                        <button type="submit" class="btn btn-warning btn-sm">Update</button>
                    </form>
                    <form method="POST" action="{% url 'cart:update_cart' product_id=item.product.id %}" class="d-inline-flex align-items-center">
                        {% csrf_token %}
                        <input type="hidden" name="qty" value=0>
                        <button type="submit" class="btn btn-sm"><i class="fas fa-trash-alt"></i></a>
                    </form>
                </td>
                <td>${{ item.line_total|floatformat:2|intcomma }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>
{% endblock %}