accounts/urls.py
from django.urls import path
from django.contrib.auth import views as aut_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('<int:profiled_user_id>', views.user_profile, name="user_profile"),
    path('<int:profiled_user_id>/update', views.update_user_profile, name="update_user_profile"),
    path('<int:profiled_user_id>/settimezone', views.set_timezone, name="set_user_timezone"),

    path('testing', views.testdata, name="test_data"),
    path('createusers', views.create_users, name="create_users"),
    path('resetusers', views.reset_users, name="reset_users"),
]

backlog/urls.py
from django.urls import path, include
from . import views

app_name = 'backlog'

urlpatterns = [
    # backlog/
    path('', views.BacklogList.as_view(), name='index'),
    path('add/', views.BacklogCreate.as_view(), name='backlog_add'),
    path('<int:pk>/', views.BacklogDetail.as_view(), name="backlog_details"),
    path('<int:pk>/update/', views.BacklogUpdate.as_view(), name="backlog_update"),
    path('<int:pk>/delete/', views.BacklogDelete.as_view(), name="backlog_delete"),
]

cart/urls.py
from django.urls import path, include, register_converter
from . import views

app_name = 'cart'

urlpatterns = [
    # cart/
    path('', views.view_cart, name="cart_details"), # views.CategoryDetail.as_view(), name="category_details"),
    path('<int:product_id>/', views.add_to_cart, name="add_to_cart"), # views.CategoryCreate.as_view(), name="category_add"),
    path('<int:product_id>/remove/', views.remove_from_cart, name="remove_from_cart"),
    path('<int:product_id>/update/', views.update_cart, name="update_cart"),
    # path('<int:pk>/delete/', views.CategoryDelete.as_view(), name="category_delete"),
    path('test/', views.test_cart, name="test_cart"),
    path('test/<int:new_cart_id>/', views.test_cart, name="test_cart"),
    path('clear-id/', views.clear_cart_id_from_session, name="clear_cart_id"),
    path('revive/', views.revive_cart, name="revive_cart"),
    path('get-id/', views.get_cart_id, name="get_cart_id"),
]

shop/urls.py
from django.urls import path, include, register_converter
from . import views, converters

app_name = 'shop'
register_converter(converters.NegativeIntConverter, 'negint')

ajax_patterns = [
    # ajax
    path('favorite/<int:product_id>/', views.ajax_favorite, name="ajax_favorite"),
    path('unfavorite/<int:product_id>/', views.ajax_unfavorite, name="ajax_unfavorite"),
]

products_patterns = [
    # products/
    # path('<int:category_id>',views.CategoryProductList.as_view(), name="category_products"),
    # path('favorites', views.FavoriteProductList.as_view(), name="favorite_products"),
    # path('search', views.search_products, name="search_products"),
    path('sale', views.SaleProductList.as_view(), name="sale_products"),
    path('recent/', views.RecentProductsView.as_view(), name="recent"),
    path('recent/clear/', views.clear_recent, name="clear_recent"),
]

product_patterns = [
    # product/
    path('add/', views.ProductCreate.as_view(), name='product_add'),
    path('<int:pk>/', views.ProductDetail.as_view(), name="product_details"),
    path('<int:pk>/update/', views.ProductUpdate.as_view(), name="product_update"),
    path('<int:pk>/delete/', views.ProductDelete.as_view(), name="product_delete"),
    path('<int:pk>/promotion/', views.PromotionCreate.as_view(), name="product_sale"),
    path('<int:product_id>/rate/', views.rate_product, name="rate_product"),
    path('<int:product_id>/question/', views.question_product, name="question_product"),
    path('<int:product_id>/favorite/', views.favorite, name="favorite"),
    path('<int:product_id>/unfavorite/', views.unfavorite, name="unfavorite"),
    path('<int:product_id>/getinfo/', views.get_product_info, name="get_product_info"),
    path('product_photo/<int:product_photo_id>/delete/', views.product_photo_delete, name="product_photo_delete"),
    path('product_photo/<int:product_photo_id>/makeprimary/', views.product_photo_make_primary, name="product_photo_make_primary"),
]

sale_patterns = [
    # sale/
    path('add/', views.SaleCreate.as_view(), name='sale_add'),
    path('<int:pk>/', views.SaleDetail.as_view(), name="sale_details"),
    path('<int:pk>/update/', views.SaleUpdate.as_view(), name="sale_update"),
    path('<int:pk>/delete/', views.SaleDelete.as_view(), name="sale_delete"),
    path('<int:sale_id>/getinfo/', views.get_sale_info, name="get_sale_info"),
]

promotion_patterns = [
    # promotion/
    path('add/', views.PromotionCreate.as_view(), name='promotion_add'),
    path('<int:pk>/', views.PromotionDetail.as_view(), name="promotion_details"),
    path('<int:pk>/update/', views.PromotionUpdate.as_view(), name="promotion_update"),
    path('<int:pk>/delete/', views.PromotionDelete.as_view(), name="promotion_delete"),
]

category_patterns = [
    # category/
    # path('', views.CategoryList.as_view(), name="categories"),
    path('add/', views.CategoryCreate.as_view(), name="category_add"),
    path('<int:pk>/', views.CategoryDetail.as_view(), name="category_details"),
    path('<int:pk>/update/', views.CategoryUpdate.as_view(), name="category_update"),
    path('<int:pk>/delete/', views.CategoryDelete.as_view(), name="category_delete"),
]

collection_patterns = [
    # collection/
    path('add/', views.CollectionCreate.as_view(), name="collection_add"),
    path('<int:pk>/', views.CollectionDetail.as_view(), name="collection_details"),
    path('<int:pk>/update/', views.CollectionUpdate.as_view(), name="collection_update"),
    path('<int:pk>/delete/', views.CollectionDelete.as_view(), name="collection_delete"),
    path('<int:collection_id>/getinfo/', views.get_collection_info, name="get_collection_info"),
]

urlpatterns = [
    path('', views.ProductList.as_view(), name='index'), #views.index, name="index"),
    path('product/', include(product_patterns)),
    path('products/', include(products_patterns)),
    path('promotion/', include(promotion_patterns)),
    path('promotions/', views.PromotionList.as_view(), name="promotions"), # list of promotions
    path('sale/', include(sale_patterns)),
    path('sales/', views.SaleList.as_view(), name="sales"), # list of sales
    path('category/', include(category_patterns)), # adding, deleting, updating, viewwing individual categories
    path('categories/', views.CategoryList.as_view(), name="categories"), # list of categories
    path('categories/<int:category_id>',views.CategoryProductList.as_view(), name="category_products"), # products related to categories    
    path('collection/', include(collection_patterns)), # adding, deleting, updating, viewwing individual collections
    path('collections/', views.CollectionList.as_view(), name="collections"), # list of collections
    path('collections/<int:collection_id>',views.CollectionProductList.as_view(), name="collection_products"), # products related to collections
    path('ajax/', include(ajax_patterns)),
    path('favorites/', views.FavoriteProductList.as_view(), name="favorite_products"),
    path('rating/<int:rating_id>/vote/<negint:score>', views.rating_vote, name="rating_vote"),
    path('question/<int:question_id>/answer', views.answer_question, name="answer_question"),
    path('question/<int:question_id>/follow', views.follow_question, name="follow_question"),
    path('question/<int:question_id>/unfollow', views.unfollow_question, name="unfollow_question"),
    path('contact/', views.ContactCreate.as_view(), name='contact-us'),
    # path('contact/success/',views.ContactSuccess.as_view(),'contact-success'),
    # path('test/', views.test, name="test"),
]

weybridge/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('registration/', include('accounts.urls')),
    path('backlog/', include('backlog.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backlog/models.py
from django.db import models
from django import forms
from django.forms import ModelForm, ValidationError
from django.contrib.auth.models import User
from django.conf import settings
from datetime import datetime, date, timedelta
from django.db.models import Avg, UniqueConstraint
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.text import slugify
from django.utils import timezone 
from django.shortcuts import reverse
# from django.utils import unique_slug_generator
import math
import string 
import random 

# def backlog_path(instance, filename):
#     # file will be uploaded to MEDIA_ROOT/dish_<id>/<filename>
#     return f'product_{instance.id}/size_chart_{filename}'

class Backlog(models.Model):
    
    class Category(models.IntegerChoices):
        URLS = 1
        VIEWS = 2
        MODELS = 3
        TEMPLATES = 4
        STATIC = 5
        ADMIN = 6
        FORMS = 7
        MEDIA = 8
        SETTINGS = 9
        SIGNALS = 10
        CONVERTERS = 11
        CUSTOM_TAGS = 12
        TESTS = 13
        OTHER = 99

    # CATEGORY_CHOICES = (
    #     (URLS, 'urls'),
    #     (VIEWS, 'views'),
    #     (MODELS, 'models'),
    #     (TEMPLATES, 'templates'),
    #     (STATIC, 'static'),
    #     (ADMIN, 'admin'),
    #     (FORMS, 'forms'),
    #     (MEDIA, 'media'),
    #     (SETTINGS, 'settings'),
    #     (SIGNALS, 'signals'),
    #     (CONVERTERS, 'converters'),
    #     (CUSTOM_TAGS, 'custom tags'),
    #     (TESTS, 'tests'),
    #     (OTHER, 'other'),
    # )

    class Status(models.IntegerChoices):
        PENDING = 1
        COMPLETED = 2
        WONT_FIX = 3

    class Priority(models.IntegerChoices):
        HIGH = 1
        MEDIUM = 2
        LOW = 3
        HORIZON = 4

    app_name = models.CharField(max_length=255)
    model_name = models.CharField(max_length=255, blank=True, null=True)
    category = models.IntegerField(
        choices=Category.choices,
        verbose_name = 'categories',
    )
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    priority = models.IntegerField(
        choices=Priority.choices,
        default = Priority.MEDIUM
    )
    status = models.IntegerField(
        choices=Status.choices,
        default = Status.PENDING,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="backlog_items_updated", on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="backlog_items_created", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('backlog:backlog_details',kwargs={'pk': self.id})

class BacklogForm(ModelForm):
    class Meta:
        model = Backlog
        fields = ['app_name', 'model_name', 'category', 'title', 'description','priority', 'status']
        widgets = {
            'app_name' : forms.TextInput(attrs={'class':'form-control'}),
            'model_name' : forms.TextInput(attrs={'class':'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'priority': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
       }

# class Entries(models.Model):

backlog/views.py
from django.views.generic import ListView,DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.shortcuts import render, redirect, reverse, get_object_or_404,HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.db.models import Avg, F, Q, Count, FilteredRelation, Value, IntegerField, CharField
from datetime import datetime
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponseNotAllowed
from .models import *
from shop.views import get_breadcrumbs

class BacklogList(ListView):
    model = Backlog

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['breadcrumbs'] = get_breadcrumbs('page',None,'Backlog')
        return context

class BacklogDetail(DetailView):
    model = Backlog

class BacklogCreate(CreateView):
    model = Backlog
    form_class = BacklogForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.updated_by = self.request.user
        return super().form_valid(form)

class BacklogUpdate(UpdateView):
    model = Backlog
    form_class = BacklogForm

    def form_valid(self, form):
        form.instance.updated_by = self.request.user
        return super().form_valid(form)

class BacklogDelete(DeleteView):
    model = Backlog
    success_url = reverse_lazy('backlog:index')
    template_name = 'shop/object_confirm_delete.html'

backlog/templates/backlog/backlog_detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'shop/css/product.css' %}">
{% endblock css %}

{% block greeting %}{% if user.is_authenticated %} {{ user.first_name }}{% else %}{% endif %}{% endblock greeting %}

{% block favorites %}
{% if user.is_authenticated %}
<a href="{% url 'shop:favorite_products' %}" class="nav-link"><i class="fas fa-bookmark"></i>Favorites</a>
{% else %}
{% endif %}
{% endblock favorites %}

{% block profile %}
{% if user.is_authenticated %}
<a href="{% url 'accounts:user_profile' profiled_user_id=user.id %}" class="nav-link"><i
        class="fas fa-user-cog"></i>Profile</a>
{% else %}
<a href="{% url 'accounts:signup' %}" class="nav-link"><i class="fas fa-user-cog"></i>Register</a>
{% endif %}
{% endblock profile %}

{% block login %}
{% if user.is_authenticated %}
<a href="{% url 'logout' %}" class="nav-link"><i class="fas fa-sign-out-alt"></i>Logout</a>
{% else %}
<a href="{% url 'login' %}" class="nav-link"><i class="fas fa-sign-in-alt"></i>Login</a>
{% endif %}
{% endblock login %}

{% block content %}
<div class="container" data-id="{{ backlog.id }}">
    {% include 'shop/breadcrumbs.html' %}

    <div class="dish-header d-flex flex-column align-items-center">

        <div class="dish-title d-inline-flex align-items-baseline">
            <h1 class="my-0">{{ backlog.title }}</h1>
            {% if request.user.is_staff %}
            <p class="edit-category ml-2 my-0" title="Edit" style="color:#009EC3">
                <a href="{% url 'backlog:backlog_update' pk=backlog.id %}">
                    <small><i class="fas fa-pen"></i> Edit</small>
                </a>
            </p>

            <p class="delete-category ml-2 my-0" title="Delete" style="color:red">
                <a href="{% url 'backlog:backlog_delete' pk=backlog.id %}">
                    <small><i class="fas fa-times" style="color:red"></i> Delete</small>
                </a>
            </p>
            {% endif %}
        </div><!-- end .dish-title -->
    </div><!-- end .dish-header-->

    <div class="row">

        <div class="col-8">
            <div class="app-name">App: {{ backlog.app_name }}</div><!-- end .description -->
            <div class="model-name">Model: {{ backlog.model_name }}</div><!-- end .retail-price -->
            <div class="category">Category: {{ backlog.get_category_display }}</div><!-- end .sale-price -->
            <div class="description">Description: 
                <div>{{ backlog.description|linebreaks }}</div>
            </div><!-- end .description -->
            <div class="priority">Priority: {{ backlog.get_priority_display }}</div><!-- end .sale -->
            <div class="status">Status: {{ backlog.get_status_display }}</div><!-- end .start-date -->
        </div><!-- end .col-8 -->
    
        <div class="col-4">
            <div id="categories">
                <!--Insert link tag to be able to take to similar category pages-->
                <p>About this item:</p>
            </div><!-- end #categories-->
        </div><!-- end .col-4 -->
    </div><!-- end .row -->

    <div class="row">
        {% if request.user.is_staff %}
        <p style="font-style: italic;"><small>Created by {{ backlog.created_by.get_full_name }} on {{ backlog.created_at }} Updated by {{ backlog.updated_by.get_full_name }} on {{ backlog.updated_at }}</small></p>
        {% endif %}
    </div>

</div>

{% endblock %}

backlog/templates/backlog/backlog_form.html
{% extends 'shop/base.html' %}
{% load static humanize %}

{% block css %}
<link rel="stylesheet" href="{% static 'shop/css/createCategory.css' %}">
{% endblock css %}

{% block content%} 
<div class="container new-backlog">
    <div class="header">
        <img src="{% static 'shop/icon_reverse.png' %}" width="40px" alt="Mich Dish logo">
        <div>
            <h1>{% block form_title %}{% endblock form_title %}</h1>
        </div>
    </div>
    <div class="product-info d-flex justify-content-center align-items-center my-2"></div>
    <div class="content">
        <form action=""
            class="backlog-form"
            enctype="multipart/form-data" 
            method="POST" 
            role="form" novalidate>
            {% csrf_token %}
            
            {% for error in form.non_field_errors %}
            <p class="alert alert-danger"><strong>{{ error }}</strong></p>
            {% endfor%}

            {% for field in form.visible_fields %}
            <div class="fieldWrapper form-group"
                data-id="{{ field.name }}" 
                aria-required="{% if field.field.required %}true{% else %}false{% endif %}">

                {% for error in field.errors %}
                <p class="alert alert-danger"><strong>{{ error }}</strong></p>
                {% endfor %}
                            
                {{ field.label_tag }}{% if field.field.required %}<span class="required">*</span>{% endif %}
                {{ field }}
                {% if field.help_text %}
                <small id="help_for_{{ field.name }}" class="form-text text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
            </div>
            {% endfor %}

            {% for field in form.hidden_fields %}
                {{ field }}
            {% endfor %}
            <div class="d-flex justify-content-center align-items-center">
                <a href="{% if request.META.HTTP_REFERER == request.build_absolute_uri %}/{% else %}{{ request.META.HTTP_REFERER }}{% endif %}" class="btn btn-outline-secondary mb-2 mx-2" role="button">Cancel</a>
                <input type="submit" class="btn btn-primary mb-2" value="Submit" />
            </div>
        </form>
    </div>
</div>
{% endblock %} 

backlog/templates/backlog/backlog_list.html
{% extends 'shop/base.html' %}
{% load static humanize shop_extras %}

{% block css %}
<link rel="stylesheet" href="{% static 'shop/css/dashboard.css' %}">
{% endblock css %}

{% block greeting %}{% if user.is_authenticated %} {{ user.first_name }}{% else %}{% endif %}{% endblock greeting %}

{% block favorites %}
{% if user.is_authenticated %}
<a href="{% url 'shop:favorite_products' %}" class="nav-link"><i class="fas fa-bookmark"></i>Favorites</a>
{% else %}
{% endif %}
{% endblock favorites %}

{% block profile %}
{% if user.is_authenticated %}
<a href="{% url 'accounts:user_profile' profiled_user_id=user.id %}" class="nav-link"><i
    class="fas fa-user-cog"></i>Profile</a>
{% else %}
<a href="{% url 'accounts:signup' %}" class="nav-link"><i class="fas fa-user-cog"></i>Register</a>
{% endif %}
{% endblock profile %}

{% block login %}
{% if user.is_authenticated %}
<a href="{% url 'logout' %}" class="nav-link"><i class="fas fa-sign-out-alt"></i>Logout</a>
{% else %}
<a href="{% url 'login' %}" class="nav-link"><i class="fas fa-sign-in-alt"></i>Login</a>
{% endif %}
{% endblock login %}



{% block content %}
{% include 'shop/breadcrumbs.html' %}

<div class="container">
    <div class="my-4">
        {% if request.user.is_staff %}
        <a href="{% url 'backlog:backlog_add' %}" class="btn btn-info"><small><i class="fas fa-plus-circle"></i> New</small></a> 
        {% endif %}
    </div>

    <table class="table">
        <thead>
            <th>App</th>
            <th>Model</th>
            <th>Category</th>
            <th>Title</th>
            <th>Priority</th>
            <th>Status</th>
        </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.app_name }}</td>
                <td>{{ item.model_name }}</td>
                <td>{{ item.get_category_display }}</td>
                <td>
                    <a href="{% url 'backlog:backlog_details' pk=item.id %}">
                        {{ item.title }}
                    </a>
                </td>
                <td>{{ item.get_priority_display }}</td>
                <td>{{ item.get_status_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock%}