accounts/urls.py
from django.urls import path
from django.contrib.auth import views as aut_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('<int:profiled_user_id>', views.user_profile, name="user_profile"),
    path('<int:profiled_user_id>/update', views.update_user_profile, name="update_user_profile"),
    path('<int:profiled_user_id>/settimezone', views.set_timezone, name="set_user_timezone"),

    path('testing', views.testdata, name="test_data"),
    path('createusers', views.create_users, name="create_users"),
    path('resetusers', views.reset_users, name="reset_users"),
]

cart/urls.py
from django.urls import path, include, register_converter
from . import views

app_name = 'cart'

urlpatterns = [
    # cart/
    path('', views.view_cart, name="cart_details"), # views.CategoryDetail.as_view(), name="category_details"),
    path('<int:product_id>/', views.add_to_cart, name="add_to_cart"), # views.CategoryCreate.as_view(), name="category_add"),
    path('<int:product_id>/remove/', views.remove_from_cart, name="remove_from_cart"),
    path('<int:product_id>/update/', views.update_cart, name="update_cart"),
    # path('<int:pk>/delete/', views.CategoryDelete.as_view(), name="category_delete"),
    path('test/', views.test_cart, name="test_cart"),
    path('test/<int:new_cart_id>/', views.test_cart, name="test_cart"),
    path('clear-id/', views.clear_cart_id_from_session, name="clear_cart_id"),
    path('revive/', views.revive_cart, name="revive_cart"),
    path('get-id/', views.get_cart_id, name="get_cart_id"),
]

shop/urls.py
from django.urls import path, include, register_converter
from . import views, converters

app_name = 'shop'
register_converter(converters.NegativeIntConverter, 'negint')

ajax_patterns = [
    # ajax
    path('favorite/<int:product_id>/', views.ajax_favorite, name="ajax_favorite"),
    path('unfavorite/<int:product_id>/', views.ajax_unfavorite, name="ajax_unfavorite"),
]

products_patterns = [
    # products/
    # path('<int:category_id>',views.CategoryProductList.as_view(), name="category_products"),
    # path('favorites', views.FavoriteProductList.as_view(), name="favorite_products"),
    # path('search', views.search_products, name="search_products"),
    path('sale', views.SaleProductList.as_view(), name="sale_products"),
    path('recent/', views.RecentProductsView.as_view(), name="recent"),
    path('recent/clear/', views.clear_recent, name="clear_recent"),
]

product_patterns = [
    # product/
    path('add/', views.ProductCreate.as_view(), name='product_add'),
    path('<int:pk>/', views.ProductDetail.as_view(), name="product_details"),
    path('<int:pk>/update/', views.ProductUpdate.as_view(), name="product_update"),
    path('<int:pk>/delete/', views.ProductDelete.as_view(), name="product_delete"),
    path('<int:pk>/promotion/', views.PromotionCreate.as_view(), name="product_sale"),
    path('<int:product_id>/rate/', views.rate_product, name="rate_product"),
    path('<int:product_id>/question/', views.question_product, name="question_product"),
    path('<int:product_id>/favorite/', views.favorite, name="favorite"),
    path('<int:product_id>/unfavorite/', views.unfavorite, name="unfavorite"),
    path('<int:product_id>/getinfo/', views.get_product_info, name="get_product_info"),
    path('product_photo/<int:product_photo_id>/delete/', views.product_photo_delete, name="product_photo_delete"),
    path('product_photo/<int:product_photo_id>/makeprimary/', views.product_photo_make_primary, name="product_photo_make_primary"),
]

sale_patterns = [
    # sale/
    path('add/', views.SaleCreate.as_view(), name='sale_add'),
    path('<int:pk>/', views.SaleDetail.as_view(), name="sale_details"),
    path('<int:pk>/update/', views.SaleUpdate.as_view(), name="sale_update"),
    path('<int:pk>/delete/', views.SaleDelete.as_view(), name="sale_delete"),
    path('<int:sale_id>/getinfo/', views.get_sale_info, name="get_sale_info"),
]

promotion_patterns = [
    # promotion/
    path('add/', views.PromotionCreate.as_view(), name='promotion_add'),
    path('<int:pk>/', views.PromotionDetail.as_view(), name="promotion_details"),
    path('<int:pk>/update/', views.PromotionUpdate.as_view(), name="promotion_update"),
    path('<int:pk>/delete/', views.PromotionDelete.as_view(), name="promotion_delete"),
]

category_patterns = [
    # category/
    # path('', views.CategoryList.as_view(), name="categories"),
    path('add/', views.CategoryCreate.as_view(), name="category_add"),
    path('<int:pk>/', views.CategoryDetail.as_view(), name="category_details"),
    path('<int:pk>/update/', views.CategoryUpdate.as_view(), name="category_update"),
    path('<int:pk>/delete/', views.CategoryDelete.as_view(), name="category_delete"),
]

collection_patterns = [
    # collection/
    path('add/', views.CollectionCreate.as_view(), name="collection_add"),
    path('<int:pk>/', views.CollectionDetail.as_view(), name="collection_details"),
    path('<int:pk>/update/', views.CollectionUpdate.as_view(), name="collection_update"),
    path('<int:pk>/delete/', views.CollectionDelete.as_view(), name="collection_delete"),
    path('<int:collection_id>/getinfo/', views.get_collection_info, name="get_collection_info"),
]

urlpatterns = [
    path('', views.ProductList.as_view(), name='index'), #views.index, name="index"),
    path('product/', include(product_patterns)),
    path('products/', include(products_patterns)),
    path('promotion/', include(promotion_patterns)),
    path('promotions/', views.PromotionList.as_view(), name="promotions"), # list of promotions
    path('sale/', include(sale_patterns)),
    path('sales/', views.SaleList.as_view(), name="sales"), # list of sales
    path('category/', include(category_patterns)), # adding, deleting, updating, viewwing individual categories
    path('categories/', views.CategoryList.as_view(), name="categories"), # list of categories
    path('categories/<int:category_id>',views.CategoryProductList.as_view(), name="category_products"), # products related to categories    
    path('collection/', include(collection_patterns)), # adding, deleting, updating, viewwing individual collections
    path('collections/', views.CollectionList.as_view(), name="collections"), # list of collections
    path('collections/<int:collection_id>',views.CollectionProductList.as_view(), name="collection_products"), # products related to collections
    path('ajax/', include(ajax_patterns)),
    path('favorites/', views.FavoriteProductList.as_view(), name="favorite_products"),
    path('rating/<int:rating_id>/vote/<negint:score>', views.rating_vote, name="rating_vote"),
    path('question/<int:question_id>/answer', views.answer_question, name="answer_question"),
    path('question/<int:question_id>/follow', views.follow_question, name="follow_question"),
    path('question/<int:question_id>/unfollow', views.unfollow_question, name="unfollow_question"),
    path('contact/', views.ContactCreate.as_view(), name='contact-us'),
    # path('contact/success/',views.ContactSuccess.as_view(),'contact-success'),
    # path('test/', views.test, name="test"),
]

weybridge/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('registration/', include('accounts.urls')),
    path('backlog/', include('backlog.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/forms.py
from django import forms

shop/views.py
from urllib.parse import urlencode
from datetime import datetime,timezone,timedelta

from django.conf import settings
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core import serializers
from django.core.mail import send_mail
from django.db.models import (
    OuterRef, Subquery, Avg, F, Q, Count, Min, FilteredRelation, Value, IntegerField, 
    CharField, BooleanField, Case, When)
from django.db.models.functions import Coalesce
from django.http import JsonResponse, HttpResponseNotAllowed
from django.shortcuts import render, redirect, reverse, get_object_or_404,HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView,DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, DeleteView, FormView, UpdateView

from ipware import get_client_ip

from .models import *
from .services import (
    RecentlyViewedItems, get_product_rating_for_user, get_category_parent,
    get_category_children, get_category_list, get_categories
)

category_qs = Category.objects.all()
throw_away_var = len(category_qs)   #force evaluation of queryset
recently_viewed_max = 4 # number of recently viewed products to store in session

class StaffMemberRequiredMixin(UserPassesTestMixin):
    # raise_exception = False

    def test_func(self):
        return self.request.user.is_staff

    def handle_no_permission(self):
        """ Do whatever you want here if the user doesn't pass the test """
        if self.request.user.is_authenticated:
            return render(self.request, 'shop/403.html')
        return super(StaffMemberRequiredMixin,self).handle_no_permission()

def test(request):
    return render(request, 'shop/test.html', {'test': 'Testing 123'})

# def get_category_parent(category_id):
#     '''
#         Returns an ordered list of category ids for all category 'ancestors'.
#         Ancestors are the parent_category for the category_id param, plus the parent's parent, etc.
#         The returned list includes the category_id param as its first item.
#     '''
#     category = Category.objects.get(id=category_id)
#     parent = category.parent_category_id or None
#     list = []
#     if parent:
#         list.extend(get_category_parent(parent))
#     list.append(category_id)
#     return list
    
# def get_category_children(category_id):
#     '''
#         Returns an ordered list of category ids for all categories that are children of the category_id param.
#         The returned list include the category_id param as its first item.
#         Different from category.child_categories in that the list is ordered and it includes the category_id param as its first item.
#     '''
#     children = Category.objects.filter(parent_category = category_id)
#     list = []
#     if children:
#         for child in children:
#             list.extend(get_category_children(child.id))
#     list.append(category_id)
#     return list

# def get_category_list(parent_category_id):
#     strHTML = ''
#     # children = Category.objects.filter(parent_category = parent_category_id).order_by('name')
#     children = category_qs.filter(parent_category = parent_category_id).order_by('name')
#     if children:
#         for child in children:
#             id_str = child.name.replace('\\','').replace(' ','_').replace('\'','').lower()
#             category_products_url = reverse('shop:category_products', kwargs={'category_id': child.id})
#             strHTML += f'<div class="category" id="category-{id_str}">'
#             strHTML += f'<a href="{category_products_url}">'
#             strHTML += child.name
#             strHTML += '</a>'
#             strHTML += get_category_list(child.id) 
#             strHTML += '</div>'    

#     return strHTML.replace('\\','')  

# def get_categories(parent_category_id,level=0):
#     categories = []
    
#     for current_category in category_qs.filter(parent_category = parent_category_id).annotate(
#         indent_level=Value(level, IntegerField()),
#         indent_px=Value(f"{level*20}px", CharField()),
#     ).order_by('name'):
#         categories.append(current_category) 
#         for child_category in get_categories(current_category.id, level+1):
#             categories.append(child_category)

#     return categories    

# def get_product_rating_for_user(user, object):
#     # returns information about whether the user has rated a particular product
 
#     if hasattr(object,'ratings'):
#         all_ratings = object.ratings.all()

#         if user.is_authenticated == False:
#             # user is anonymous, so user has not yet rated item yet
#             user_has_rated_item = False
#             user_rating_this_item = None
#             form = RatingForm()

#         # determine if this user has rated this item before
#         elif all_ratings.filter(user=user).count() > 0:
#             #user hsa rated item; don't permit another rating (just don't return a form object)
#             # print(f"Ratings for {object}: {all_ratings.filter(user=user).count()}")
#             user_has_rated_item = True
#             user_rating_this_item = all_ratings.filter(user=user).first()
#             form = None

#         else:
#             # user has not yet rated this item
#             user_has_rated_item = False
#             user_rating_this_item = None
#             form = RatingForm()

#         # #get the oversall ratings for this item
#         # average_rating = object.ratings.aggregate(Avg('number_of_stars'))['number_of_stars__avg'] or 0
        
#         # upvotes = Count('votes__score_type', filter=Q(votes__score_type=1))
#         # downvotes = Count('votes__score_type', filter=Q(votes__score_type=-1))
#         # all_ratings = object.ratings.annotate(upvotes=upvotes).annotate(downvotes=downvotes).order_by('-created_at')       

#     else:
#         # item has no ratings yet
#         print(f"No ratings yet for {object}.")
#         form = RatingForm()
#         average_rating = 0
#         all_ratings = None

#     rating_info = {
#         'user': user,
#         'object': object,
#         # 'average_rating': average_rating,
#         # 'all_ratings': all_ratings,
#         'user_has_rated_item': user_has_rated_item,
#         'user_rating_this_item': user_rating_this_item,
#         'form': form,
#     }
#     return rating_info

def get_breadcrumbs(page_type,item_id, breadcrumb_name=None, url=None):
    """
        Returns breadcrumbs for pages based on page type, item on page, etc.
    """
    home = {
        'type':'home',
        'id': 0,
        'name': 'home'
    }
    categories = [home]

    if page_type == 'product': #product details page
        #get product category
        product_object = Product.objects.get(id=item_id)
        category_object = product_object.categories.first()
        category_list = get_category_parent(category_object.id)
        for category in category_list:
            categories.append ({
                "type": 'category',
                "id": category,
                "name": Category.objects.get(id=category).name,
            })
        categories.append ({
            "type": "product",
            "id": -1,
            "name": product_object.name,
        })
    elif page_type == 'category':   #category products list
        # category_object = Category.objects.get(id=item_id)
        category_list = get_category_parent(item_id)
        for category in category_list:
            categories.append ({
                "type": 'category',
                "id": category,
                "name": Category.objects.get(id=category).name,
            })
    elif page_type == 'collection' or page_type == 'sale' or page_type == 'promotion':   
        categories.append ({
            "type": 'page',
            "id": -1,
            "name": f"{page_type.capitalize()}s",
            "url": url,
        })
        categories.append({
            "type": 'page',
            "id": -1,
            "name": breadcrumb_name #Collection.objects.get(id=item_id).name,
        })
    else:
        categories.append ({
            "type": 'other',
            "id": None,
            "name": breadcrumb_name,
        })

    return categories

@login_required
def rate_product(request, product_id):
    # This view can be called via Ajax and returns only the ratings form

    user = request.user
    product = Product.objects.get(id=product_id)

    # print(f'Processing rating of product '{product.name}' by {user.full_name()}')
    if request.method == 'POST':

        rating = Rating(user=user, product=product,updated_by=user)
        form = RatingForm(request.POST, instance=rating)
        if form.is_valid():
            rating = form.save()
    
    else: #this is a GET request so return to the details page where the blank rating form is displayed
        return redirect(reverse('product_details'))
    
    if hasattr(product,'ratings'):
        # if user has rated item, don't let user rate it again
        # get user's rating for this item
        if product.ratings.filter(user=user).count() > 0:
            user_has_rated_item = True
            user_rating_this_item = product.ratings.filter(user=user).first()
            form = None #don't return a form

        else:
            user_has_rated_item = False
            user_rating_this_item = None

        #recalculate average ratings
        average_rating = Rating.objects.filter(product=product).aggregate(Avg('number_of_stars'))['number_of_stars__avg'] or 0
        all_ratings = product.ratings.all()

    else:
        average_rating = 0
        all_ratings = None

    context = {

shop/templates/shop/action-unfavorite.html
<a href="{% url 'shop:favorite' product_id=product.id %}" title="Favorite">
    <span style="color:gray;"><i class="fas fa-heart"></i></span>
</a>

shop/templates/shop/category_form.html
{% extends 'shop/generic_form.html' %}
{% load static %}

{% block form_title %}
    {{ action|capfirst }} Category
{% endblock form_title %}

shop/templates/shop/category_products.html
{% extends 'shop/base.html' %}
{% load static shop_extras %}
{% block css %}
<link rel="stylesheet" href="{% static 'shop/css/favorites.css' %}">
{% endblock css %}

{% block greeting %}{% if user.is_authenticated %} {{ user.first_name }}{% else %}{% endif %}{% endblock greeting %}

{% block favorites %}
{% if user.is_authenticated %}
<a href="{% url 'shop:favorite_products' %}" class="nav-link"><i class="fas fa-bookmark"></i>Favorites</a>
{% else %}
{% endif %}
{% endblock favorites %}

{% block profile %}
{% if user.is_authenticated %}
<a href="{% url 'accounts:user_profile' profiled_user_id=user.id %}" class="nav-link"><i
        class="fas fa-user-cog"></i>Profile</a>
{% else %}
<a href="{% url 'accounts:signup' %}" class="nav-link"><i class="fas fa-user-cog"></i>Register</a>
{% endif %}
{% endblock profile %}

{% block login %}
{% if user.is_authenticated %}
<a href="{% url 'logout' %}" class="nav-link"><i class="fas fa-sign-out-alt"></i>Logout</a>
{% else %}
<a href="{% url 'login' %}" class="nav-link"><i class="fas fa-sign-in-alt"></i>Login</a>
{% endif %}
{% endblock login %}


{% block content %}
    {% include 'shop/breadcrumbs.html' %}

    {% sidebar %}
    
    {% include 'shop/products.html' with category_id=categories_query_string %}
{% endblock%}

shop/templates/shop/contact_form.html
{% extends 'shop/generic_form.html' %}
{% load static shop_extras %}

{% block form_title %}
Contact Us
{% endblock form_title %}

shop/templates/shop/product_list.html
{% extends 'shop/base.html' %}
{% load static %}
{% load shop_extras %}

{% block css %}
<link rel="stylesheet" href="{% static 'shop/css/dashboard.css' %}">
{% endblock css %}

{% block greeting %}{% if user.is_authenticated %} {{ user.first_name }}{% else %}{% endif %}{% endblock greeting %}

{% block favorites %}
{% if user.is_authenticated %}
<a href="{% url 'shop:favorite_products' %}" class="nav-link"><i class="fas fa-bookmark"></i>Favorites</a>
{% else %}
{% endif %}
{% endblock favorites %}

{% block profile %}
{% if user.is_authenticated %}
<a href="{% url 'accounts:user_profile' profiled_user_id=user.id %}" class="nav-link"><i
    class="fas fa-user-cog"></i>Profile</a>
{% else %}
<a href="{% url 'accounts:signup' %}" class="nav-link"><i class="fas fa-user-cog"></i>Register</a>
{% endif %}
{% endblock profile %}

{% block login %}
{% if user.is_authenticated %}
<a href="{% url 'logout' %}" class="nav-link"><i class="fas fa-sign-out-alt"></i>Logout</a>
{% else %}
<a href="{% url 'login' %}" class="nav-link"><i class="fas fa-sign-in-alt"></i>Login</a>
{% endif %}
{% endblock login %}

{% block content %}
    {% include 'shop/hero.html' %}
    {% sidebar %}
    {% include 'shop/products.html' %}
{% endblock content %}

shop/templates/shop/ratingForm.html
<form class="ratings-form" action="{% url 'shop:rate_product' product_id=product.id %}"
        enctype="multipart/form-data" 
        method="POST" 
        role="form" novalidate>
        {% csrf_token %}
                    
        {% for field in form.visible_fields %}
        <div class="fieldWrapper form-group"
            data-id="{{ field.name }}" 
            aria-required="{% if field.field.required %}true{% else %}false{% endif %}">
            {% for error in field.errors %}
            <p class="alert alert-danger"><strong>{{ error }}</strong></p>
            {% endfor %}
                        
            {{ field.label_tag }}{% if field.field.required %}<span class="required">*</span>{% endif %}
            {{ field }}
            {% if field.help_text %}
            <small id="help_for_{{ field.name }}" class="form-text text-muted">{{ field.help_text|safe }}</small>
            {% endif %}
        </div>
        {% endfor %}

        {% for field in form.hidden_fields %}
            {{ field }}
        {% endfor %}
        <input type="submit" class="btn btn-primary mb-2" value="Submit" />
    </form>

shop/templates/shop/sale_form.html
{% extends 'shop/generic_form.html' %}
{% load static humanize %}

{% block form_title %}
    {{ action|capfirst }} Sale
{% endblock form_title %}

shop/templates/shop/sale_list.html
{% extends 'shop/base.html' %}
{% load static humanize shop_extras %}

{% block css %}
<link rel="stylesheet" href="{% static 'shop/css/dashboard.css' %}">
{% endblock css %}

{% block greeting %}{% if user.is_authenticated %} {{ user.first_name }}{% else %}{% endif %}{% endblock greeting %}

{% block favorites %}
{% if user.is_authenticated %}
<a href="{% url 'shop:favorite_products' %}" class="nav-link"><i class="fas fa-bookmark"></i>Favorites</a>
{% else %}
{% endif %}
{% endblock favorites %}

{% block profile %}
{% if user.is_authenticated %}
<a href="{% url 'accounts:user_profile' profiled_user_id=user.id %}" class="nav-link"><i
    class="fas fa-user-cog"></i>Profile</a>
{% else %}
<a href="{% url 'accounts:signup' %}" class="nav-link"><i class="fas fa-user-cog"></i>Register</a>
{% endif %}
{% endblock profile %}

{% block login %}
{% if user.is_authenticated %}
<a href="{% url 'logout' %}" class="nav-link"><i class="fas fa-sign-out-alt"></i>Logout</a>
{% else %}
<a href="{% url 'login' %}" class="nav-link"><i class="fas fa-sign-in-alt"></i>Login</a>
{% endif %}
{% endblock login %}



{% block content %}
{% include 'shop/breadcrumbs.html' %}

{% sidebar %}

<div class="container">
    <div class="my-4">
        {% if request.user.is_staff %}
        <a href="{% url 'shop:sale_add' %}" class="btn btn-info"><small><i class="fas fa-plus-circle"></i> New</small></a> 
        {% endif %}
    </div>

    <table class="table">
        <thead>
            <th>Sale</th>
            <th>Promo Code</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Actions</th>
        </thead>
        <tbody>
            {% for sale in object_list %}
            <tr>
                <td>
                    <img src="{{ sale.profile_pic.url }}" alt="{{ sale.name }}" style="width:30px;">
                    <a href="{% url 'shop:sale_details' pk=sale.id %}">
                        {{ sale.name }} ({{ sale.promotions.count }} item{{sale.promotions.count|pluralize}})
                    </a>
                </td>
                <td>{{ sale.promo_code }}</td>
                <td>{{ sale.start_date }}</td>
                <td>{{ sale.end_date }}</td>
                <td>
                    <ul class="actions">
                        <li>
                            <a href="{% url 'shop:sale_update' pk=sale.id %}">
                                <small><i class="fas fa-pen"></i>Edit</small>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'shop:sale_delete' pk=sale.id %}">
                                <small><i class="fas fa-times" style="color:red"></i>Delete</small>
                            </a>
                        </li>
                    </ul>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock%}

shop/templates/shop/sale_products.html
{% extends 'shop/base.html' %}
{% load static humanize shop_extras %}
{% block css %}
<link rel="stylesheet" href="{% static 'shop/css/favorites.css' %}">
{% endblock css %}

{% block greeting %}{% if user.is_authenticated %} {{ user.first_name }}{% else %}{% endif %}{% endblock greeting %}

{% block favorites %}
{% if user.is_authenticated %}
<a href="{% url 'shop:favorite_products' %}" class="nav-link"><i class="fas fa-bookmark"></i>Favorites</a>
{% else %}
{% endif %}
{% endblock favorites %}

{% block profile %}
{% if user.is_authenticated %}
<a href="{% url 'accounts:user_profile' profiled_user_id=user.id %}" class="nav-link"><i
    class="fas fa-user-cog"></i>Profile</a>
{% else %}
<a href="{% url 'accounts:signup' %}" class="nav-link"><i class="fas fa-user-cog"></i>Register</a>
{% endif %}
{% endblock profile %}

{% block login %}
{% if user.is_authenticated %}
<a href="{% url 'logout' %}" class="nav-link"><i class="fas fa-sign-out-alt"></i>Logout</a>
{% else %}
<a href="{% url 'login' %}" class="nav-link"><i class="fas fa-sign-in-alt"></i>Login</a>
{% endif %}
{% endblock login %}


{% block content %} 

    {% include 'shop/breadcrumbs.html' %}

    {% sidebar %}

    {% include 'shop/products.html' %}
{% endblock%}

shop/templates/shop/userProfile.html
{% extends 'dish/base.html' %}
{% load static %}
{% block greeting %}
  {% if user.is_authenticated %}
     {{ user.first_name }}
  {% else %}
  {% endif %}
{% endblock greeting %}

{% block favorites %}
{% if user.is_authenticated %}
  <a href="{% url 'shop:favorite_products' %}" class="nav-link"><i class="fas fa-bookmark"></i>Favorites</a>
  {% else %}
  {% endif %}
{% endblock favorites %}

{% block profile %}
{% if user.is_authenticated %}
<a href="{% url 'accounts:user_profile' profiled_user_id=user.id %}" class="nav-link"><i class="fas fa-user-cog"></i>Profile</a>
{% else %}
<a href="{% url 'accounts:signup' %}" class="nav-link"><i class="fas fa-user-cog"></i>Register</a>
{% endif %}
{% endblock profile %}

{% block login %}
{% if user.is_authenticated %}
  <a href="{% url 'logout' %}" class="nav-link"><i class="fas fa-sign-out-alt"></i>Logout</a>
  {% else %}
  <a href="{% url 'login' %}" class="nav-link"><i class="fas fa-sign-in-alt"></i>Login</a>
  {% endif %}
{% endblock login %}

{% block content %}
              <div id="main-content">
                <div class="row" id="newPost">
                  <div class="col">
                        <div id="profilePic">
                          <h4>Profile Picture Should go here</h4>
                          <!--<img src="{{ profiled_user.profile_pic.url }}" alt="User Profile Picture">-->
                          <!-- Display User Profile Image (if none Display Default Image) -->
                        </div>
                        <div id="userInfo">
                          <!-- Dispaly User Info (Name, Bio, Location, Avg. Rating) -->
                          <h4>Name: {{ user.first_name }} {{ user.last_name }}</h4>
                          <h4>Bio: <p>{{ user.bio }}</p> </h4>
                          <h4>Location: {{ user.location }}</h4>
                          <h4>Birthday: {{ user.birthday }}</h4>
                        </div>
                  </div>
                  <div class="col">
                      <h4>My Post</h4>
                      <!--Dispaly All User Post-->

                  </div>
                </div>
              </div>
      {% endblock %}